image_path: './images/test/bosch_and_benz.jpg'

circle_region:
  ksize: 3
  blockSize: 11
  C: 2
  anchor: [3, 3]
  iterations: 1
  param1: 300
  param2: 30
  minRadius: 1
  maxRadius: 100

vis_circle_det:
  result: true
  inter: false

template_path: './images/templates/benz_template.jpg'
score_thres: 0.35
vis_det: true